### PR TITLE
Technical draft for preloading images

### PR DESCRIPTION
**Pull request by kiselli**
Here is my first draft for #25 

The code is not very beautiful, I just want to have feedback. 
Some work has to be done to capture some corner cases.

Feel free to review!

### CODE REVIEW

**Comment by tobias-kuendig** [comment]
Thank you very much for the work on this! 

Would you mind testing the updated version from our [preload](https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/tree/preloader) branch?

I'll release this as a new version if everything works.

**Comment by kiselli** [comment]
Very cool, thanks! 

I Found two Issues while testing the branch.

1. I'm getting: `Failed to process: DOMDocument::loadHTML(): Empty string supplied as input`  for an empty page from StaticPage Plugin. We should test for empty string.

2. I found an Issue regarding the generation of referenced Pages.

https://github.com/OFFLINE-GmbH/oc-responsive-images-plugin/blob/c14e9d013483bb4836119fd901abc29a9d50ea0a/classes/ImagePreloader.php#L163

should be `foreach ($definition['cmsPages'] as $cmsPage => $name) {` due to the structure of the 'cmsPages' Array.

**Comment by kiselli** [comment]
I Found another big issue with += array operator.  += merges the arrays (duplicate keys will be overridden)
> The + operator returns the right-hand array appended to the left-hand array; for keys that exist in both arrays, the elements from the left-hand array will be used, and the matching elements from the right-hand array will be ignored.
ref: http://php.net/manual/en/language.operators.array.php

**Comment by tobias-kuendig** [comment]
Released as v1.2.0, thanks for your work!

**Pull request merged**
